// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWnyj0wf7-9AjO-eTjGPzpLdWxSmvHFE',
    appId: '1:524542577375:web:47124a71d32e2d8211776a',
    messagingSenderId: '524542577375',
    projectId: 'tfauthexample',
    authDomain: 'tfauthexample.firebaseapp.com',
    storageBucket: 'tfauthexample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIqB0AHgg6e-4jBM_zOZCl7QpTSlmdsns',
    appId: '1:524542577375:android:139a524640bb62d911776a',
    messagingSenderId: '524542577375',
    projectId: 'tfauthexample',
    storageBucket: 'tfauthexample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7qqFG63_UvU1aMhn3bKOB8GNIk_gpCg',
    appId: '1:524542577375:ios:78cde819da40a63511776a',
    messagingSenderId: '524542577375',
    projectId: 'tfauthexample',
    storageBucket: 'tfauthexample.appspot.com',
    androidClientId: '524542577375-5qf0f4mnl53h1via6mca69esqqc5r6mn.apps.googleusercontent.com',
    iosClientId: '524542577375-q7lmhenghrrnl98lsd0h8uafgaspa6id.apps.googleusercontent.com',
    iosBundleId: 'com.tf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7qqFG63_UvU1aMhn3bKOB8GNIk_gpCg',
    appId: '1:524542577375:ios:7bbb79b074ab0eb911776a',
    messagingSenderId: '524542577375',
    projectId: 'tfauthexample',
    storageBucket: 'tfauthexample.appspot.com',
    androidClientId: '524542577375-5qf0f4mnl53h1via6mca69esqqc5r6mn.apps.googleusercontent.com',
    iosClientId: '524542577375-1tgj6fgjafvqbvg0f2ca9uc22lodqm2d.apps.googleusercontent.com',
    iosBundleId: 'com.',
  );
}
